name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2.0.0
      with:
          dotnet-version: 6.0.x
    - name: Install DocFX
      shell: pwsh
      run: choco install docfx
    - name: Build Docs
      shell: pwsh
      run: docfx ./Docs/docfx.json
      continue-on-error: false
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES }}
        external_repository: CosmosOS/cosmosos.github.io
        publish_branch: master
        publish_dir: ./Docs/_site
